### ISSUE TITLE
No 'Bookinfo'-Template available

### ISSUE THREAD

**Issue by hauschke** [theithec/bookhelper#2]
URL: https://handbuch.tib.eu/w/Spezial:BookPublisher

> Seite vorhanden? ... OK
> In Kategorie "Buch"? ... OK
> Template "Bookinfo" gefunden? ... Kein 'Bookinfo'-Template gefunden

**Comment by theithec** [comment]
For [handbuch.io](handbuch.io) related issues please contact the [Open Science Lab at the TIB](https://www.tib.eu/de/forschung-entwicklung/open-science/).

This beeing said, to use the new features, a book needs to include the new template "bookinfo" (instead of "booktitle").
